@startuml ESP32DG

database DB
participant MobileApp
participant CloudServer
actor User

==Login==
User -> MobileApp: introducere date login
MobileApp -> CloudServer: trimitere {User:[username, parola]}
CloudServer -> DB: interogare cu datele contului
alt Date Valide
    DB --> CloudServer: ok
    CloudServer --> MobileApp: login successfully
else
    DB --> CloudServer: nok
    CloudServer --> MobileApp: login failed
end
==Introducere date==
User -> MobileApp:  introducere date{tensiune arteriala,greutate,temperatura,glicemie}
MobileApp -> MobileApp : verificare date
opt parametrii_fiziologici_anormali
    MobileApp -> CloudServer: alarma detectata
    CloudServer -> DB: cerere scriere alarma
end
MobileApp -> CloudServer: date introduse
CloudServer -> DB: cerere scriere date introduse
DB --> CloudServer: date scrise ok
CloudServer --> MobileApp: ok
==Vizualizare fisa medicala==
User -> MobileApp: cerere vizualizare fisa
MobileApp -> CloudServer: cerere fisa medicala
CloudServer -> DB: interogare fisa medicala
DB --> CloudServer: date fisa medicala
CloudServer --> MobileApp: trimitere informatii fisa medicala
MobileApp -> User: afisare fisa medicala
==Vizualizare lista pacienti==
User -> MobileApp: cerere lista pacienti
MobileApp -> CloudServer: cerere lista pacienti
CloudServer -> DB: interogare lista pacienti
DB --> CloudServer: lista pacienti
CloudServer --> MobileApp: lista pacienti
MobileApp --> User: lista pacienti
==Reset Password==
User -> MobileApp: scriere date reset password {[parola_veche, parola_noua, confirmare_parola_noua]}
MobileApp -> CloudServer: cerere reset password
CloudServer -> DB: interogare parola_DB == parola_veche
alt Date Valide
    CloudServer -> DB: update parola noua
    DB --> CloudServer: update ok
    CloudServer --> MobileApp: ok
    MobileApp -> MobileApp: parola actualizata
else Date Invalide
    CloudServer --> MobileApp: nok
    MobileApp -> MobileApp: eroare la schimbarea parolei
end

@enduml