@startuml ESP32DG

database DB
participant MobileApp
participant CloudServer

==Login==
MobileApp -> MobileApp: citire date {User:[username, parola]}
MobileApp -> CloudServer: trimitere {User:[username, parola]}
CloudServer -> DB: interogare cu datele contului
alt Date Valide
    DB --> CloudServer: ok
    CloudServer --> MobileApp: login successfully
else
    DB --> CloudServer: nok
    CloudServer --> MobileApp: login failed
end
==Introducere date==
MobileApp -> MobileApp:  citire date{tensiune arteriala,greutate,temperatura,glicemie}
MobileApp -> MobileApp : verificare date
opt parametrii_fiziologici_anormali
    MobileApp -> CloudServer: alarma detectata
    CloudServer -> DB: cerere scriere alarma
end
MobileApp -> CloudServer: date introduse
CloudServer -> DB: cerere scriere date introduse
==Vizualizare fisa medicala==
MobileApp -> CloudServer: cerere fisa medicala
CloudServer -> DB: interogare fisa medicala
DB --> CloudServer: date fisa medicala
CloudServer --> MobileApp: trimitere informatii fisa medicala
MobileApp -> MobileApp: afisare fisa medicala
==Vizualizare lista pacienti==
MobileApp -> CloudServer: cerere lista pacienti
CloudServer -> DB: interogare lista pacienti
DB --> CloudServer: lista pacienti
CloudServer --> MobileApp: lista pacienti

@enduml