@startuml adaugare_pacienti

database DB
participant CloudServer
participant WebApp
actor User

User -> WebApp: introducere date cont
WebApp -> CloudServer: cerere adaugare cont
CloudServer -> DB: cerere adaugare cont
DB -> DB: incercare adaugare cont

alt operatie efectuata cu success
    DB --> CloudServer: ok
    CloudServer --> WebApp: cont creat cu succes (verificati emailul)
    WebApp --> User: ok
else operatie esuata
    DB --> CloudServer: nok
    CloudServer --> WebApp: eroare la crearea contului
    WebApp --> User: nok
end

@enduml