@startuml Adaugare_pacienti

database DB
participant CloudServer
participant WebApp
actor User

User -> WebApp: Introducere date cont
WebApp -> CloudServer: Cerere adaugare cont
CloudServer -> DB: Cerere adaugare cont
DB -> DB: Incercare adaugare cont

alt Operatie efectuata cu success
    DB --> CloudServer: Succes
    CloudServer --> WebApp: Cont creat cu succes (verificati emailul)
    WebApp --> User: Succes
else Operatie esuata
    DB --> CloudServer: Eroare
    CloudServer --> WebApp: Eroare la crearea contului
    WebApp --> User: Eroare
end

@enduml