@startuml Chat

participant DB
participant CloudServer
participant WebApp
actor User

User -> WebApp: Introducere mesaj
WebApp -> CloudServer: Cerere de trimitere mesaj
CloudServer -> DB: Salvare mesaj în baza de date
DB --> CloudServer: Confirmare salvare mesaj
CloudServer --> WebApp: Succes
WebApp --> User: Actualizare UI pentru mesaj trimis

@enduml