@startuml creare_recomandare

database DB
participant CloudServer
participant WebApp
participant MobileApp
Actor User

User -> WebApp: Introducere recomandare
WebApp -> CloudServer: Cerere scriere recomandare
CloudServer -> DB: Scrie recomandare

alt alarma scrisa
    DB --> CloudServer: Confirmare recomandare
    CloudServer --> WebApp: ok
    CloudServer -> MobileApp: push notification
    WebApp --> User: ok
else
    DB --> CloudServer: Failed
    CloudServer --> WebApp: nok
    WebApp --> User: nok
end

@enduml