@startuml Creare_recomandare

database DB
participant CloudServer
participant MobileApp
participant WebApp
Actor User

User -> WebApp: Introducere recomandare
WebApp -> CloudServer: Cerere scriere recomandare
CloudServer -> DB: Scrie recomandare

alt Alarma scrisa
    DB --> CloudServer: Confirmare recomandare
    CloudServer --> WebApp: Succes
    CloudServer -> MobileApp: Push notification
    WebApp --> User: Mesaj
else Eroare
    DB --> CloudServer: Failed
    CloudServer --> WebApp: Eroare
    WebApp --> User: Mesaj
end

@enduml