@startuml Informatii_tratament

database DB
participant CloudServer
participant WebApp
actor User

User -> WebApp: Introducere informatii tratament
WebApp -> CloudServer: Cerere scriere tratament
CloudServer -> DB: Cerere scriere tratament
DB -> DB: Incercare adaugare tratament

alt Operatie efectuata cu success
    DB --> CloudServer: Succes
    CloudServer --> WebApp: Adaugare tratament
    WebApp --> User: Mesaj
else operatie esuata
    DB --> CloudServer: Eroare
    CloudServer --> WebApp: Eroare adaugare tratament
    WebApp --> User: Mesaj
end

@enduml