@startuml informatii_tratament

database DB
participant CloudServer
participant WebApp
actor User

User -> WebApp: introducere informatii tratament
WebApp -> CloudServer: cerere scriere tratament
CloudServer -> DB: cerere scriere tratament
DB -> DB: incercare adaugare tratament

alt operatie efectuata cu success
    DB --> CloudServer: ok
    CloudServer --> WebApp: adaugare tratament
    WebApp --> User: ok
else operatie esuata
    DB --> CloudServer: nok
    CloudServer --> WebApp: eroare adaugare tratament
    WebApp --> User: nok
end

@enduml