@startuml intocmire_rapoarte

database DB
participant CloudServer
participant WebApp

WebApp -> WebApp: citire informatii raport
WebApp -> CloudServer: cerere scriere raport
CloudServer -> DB: cerere scriere raport
DB -> DB: incercare adaugare raport

alt operatie efectuata cu success
 DB -> CloudServer: ok
       CloudServer -> WebApp: adaugare raport
       WebApp -> WebApp: mesaj catre user (raportul a fost intocmit)
   else operatie esuata
       DB -> CloudServer: nok
       CloudServer -> WebApp: eroare adaugare raport
       WebApp -> WebApp: mesaj catre user (eroare)

end

@enduml