@startuml Modificare_date_pacient

database DB
participant CloudServer
participant WebApp
actor User

User -> WebApp: Introducere date modificate
WebApp -> CloudServer: Cerere modificare date
CloudServer -> DB: Cerere modificare date
DB -> DB: Incercare modificare date
alt Operatie efectuata cu succes
    DB --> CloudServer: Succes
    CloudServer --> WebApp: Date modificate cu succes
    WebApp --> User: Mesaj
else Operatie esuata
    DB --> CloudServer: Eroare
    CloudServer --> WebApp: Eroare modificare date
    WebApp --> User: Mesaj
end
@enduml