@startuml Reset_password

database DB
participant CloudServer
participant WebApp
actor User

User -> WebApp: Citire reset password {[parola_veche, parola_noua, confirmare_parola_noua]}
WebApp -> CloudServer: Cerere reset password
CloudServer -> DB: Interogare parola_DB == parola_veche
alt Date Valide
    CloudServer -> DB: Update parola noua
    DB --> CloudServer: Update ok
    CloudServer --> WebApp: Succes
    WebApp --> User: parola actualizata
else Date Invalide
    CloudServer --> WebApp: Eroare
    WebApp --> User: Eroare la schimbarea parolei
end

@enduml