@startuml reset_password

database DB
participant WebApp
participant CloudServer
actor User

User -> WebApp: citire reset password {[parola_veche, parola_noua, confirmare_parola_noua]}
WebApp -> CloudServer: cerere reset password
CloudServer -> DB: interogare parola_DB == parola_veche
alt Date Valide
    CloudServer -> DB: update parola noua
    DB --> CloudServer: update ok
    CloudServer --> WebApp: ok
    WebApp --> User: parola actualizata
else Date Invalide
    CloudServer --> WebApp: nok
    WebApp --> User: eroare la schimbarea parolei
end

@enduml