@startuml Rezolvare_tratament

database DB
participant CloudServer
participant WebApp
participant MobileApp
actor User

User -> MobileApp: Bifare tratament
MobileApp -> CloudServer: Cerere rezolvare tratament
CloudServer -> DB: Rezolvare tratament

alt Tratament rezolvat
    DB->CloudServer: Confirmare rezolvare tratament
    CloudServer->WebApp: Succes
    CloudServer -> MobileApp: push notification
    WebApp-> User: Tratamentul s-a rezolvat
else Eroare
    DB->CloudServer: Failed
    CloudServer->WebApp: Eroare
    CloudServer -> MobileApp: Push notification
    WebApp-> User: Mesaj tratamentul nu a fost rezolvata
end

@enduml