@startuml rezolvare_alarme

database DB
participant CloudServer
participant WebApp
actor User

User -> WebApp: Bifare alarma
WebApp -> CloudServer: Cerere rezolvare alarma
CloudServer -> DB: Rezolvare alarma

alt Alarma rezolvata
    DB --> CloudServer: Confirmare rezolvare alarma
    CloudServer --> WebApp: Succes
    WebApp --> User: Alarma s-a rezolvat
else
    DB --> CloudServer: Failed
    CloudServer --> WebApp: Eroare
    WebApp --> User: Alarma NU s-a rezolvat
end

@enduml