@startuml Signup

database DB
participant CloudServer
participant WebApp
actor User

User -> WebApp: Introducere date de inregistrare
WebApp -> CloudServer: Cerere creare cont
CloudServer -> CloudServer: Generare parola cont
CloudServer -> DB: Cerere adaugare cont
DB -> DB: Incercare adaugare cont

alt Operatie efectuata cu success
    DB --> CloudServer: Succes
    CloudServer --> WebApp: Cont creat cu succes (verificati emailul)
    WebApp -> User: Mesaj 
else Operatie esuata
    DB --> CloudServer: Eroare
    CloudServer --> WebApp: Eroare la crearea contului
    WebApp -> User: Mesaj 
end

@enduml