@startuml Stabilire_alarma

database DB
participant CloudServer
participant WebApp
actor User

User -> WebApp: Introducere scenariu nou alarma
WebApp -> CloudServer: Cerere scriere scenariu nou alarma
CloudServer -> DB: Scrie scenariu nou alarma

alt Alarma scrisa
    DB --> CloudServer: Confirmare scenariu salvat
    CloudServer --> WebApp: Succes
    WebApp -> User: Mesaj
else Eroare
    DB --> CloudServer: Failed
    CloudServer --> WebApp: Eroare
    WebApp -> User: Mesaj
end

@enduml