@startuml Vizualizare_date_pacient

database DB
participant CloudServer
participant WebApp
actor User

User -> WebApp: Cerere vizualizare grafice
WebApp -> CloudServer: Cerere vizualizare grafice
CloudServer -> DB: Cerere vizualizare grafice
alt Exista date
    DB -> CloudServer: Trimite datele(ta, puls, temperatura, greutate, glicemie)
    CloudServer -> WebApp: Trimite datele
    WebApp -> WebApp: Creare grafice
    WebApp -> User: Afisare date
else Nu exista date
    DB -> CloudServer: Nu exista date
    CloudServer -> WebApp: Nu exista date
    WebApp -> User: Mesaj
end

@enduml