@startuml Vizualizare_fisa

database DB
participant CloudServer
participant WebApp
actor User

User -> WebApp: Cerere vizualizare fisa
WebApp -> CloudServer: Cerere vizualizare fisa
CloudServer -> DB: Cerere vizualizare fisa
alt Exista date
    DB -> CloudServer: Trimitere datele
    CloudServer -> WebApp: Trimite datele
    WebApp -> WebApp: Creare fisa
    WebApp -> User: Afisare fisa
else Nu exista date
    DB -> CloudServer: Nu exista date
    CloudServer -> WebApp: Nu exista date
    WebApp -> User: Mesaj
end

@enduml